/**
 * @file packages/ai-client/src/types/provider.interface.ts
 * @description Master provider-agnostic interface implemented by all AI model adapters.
 * @module @yuva-devlab/ai-client
 */

import type { LLMRequest } from "./request.types";
import type { LLMResponse, LLMStreamChunk } from "./response.types";

/**
 * Universal interface for LLM adapters across local, edge, and cloud providers.
 *
 * All adapters (Ollama, Groq, Google, OpenAI, Anthropic, FallbackCascade)
 * implement this exact interface to enable seamless polymorphism.
 *
 * @example
 * ```typescript
 * const provider: ILLMProvider = new OpenAIAdapter({ apiKey: "..." });
 * const res = await provider.complete({
 *   model: "gpt-4o-mini",
 *   messages: [createUserMessage("Hello!")],
 * });
 * console.log(res.text);
 * ```
 */
export interface ILLMProvider {
  /** Unique provider slug (e.g. "ollama", "groq", "google", "openai", "anthropic", "fallback-cascade") */
  readonly name: string;

  /**
   * Executes a synchronous full completion against the model.
   *
   * @param request - Validated request payload containing model, messages, and options.
   * @returns Complete model response including text, finish reason, and token usage metrics.
   */
  complete(request: LLMRequest): Promise<LLMResponse>;

  /**
   * Streams completion tokens incrementally as they are generated by the model.
   *
   * @param request - Validated request payload containing model, messages, and options.
   * @returns Async iterable yielding token delta chunks.
   */
  stream(request: LLMRequest): AsyncIterable<LLMStreamChunk>;

  /**
   * Optional token estimation utility for budget and quota calculations.
   *
   * @param text - Input text string to count.
   * @returns Estimated token count.
   */
  countTokens?(text: string): Promise<number>;
}
