name: "📦 Release"

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release:
    name: "Version & Publish to npm"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node & Turborepo
        uses: ./.github/actions/setup-node-env

      - name: Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm run version-packages
          publish: pnpm run release
          title: "chore(release): version packages 🚀"
          commit: "chore(release): version packages 🚀"
        env:
          GITHUB_TOKEN: ${{ secrets.AUTO_PR_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
